### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by medicenplex** [matheeshapathirana/YouTube-Viewer-Bot#1]
![imagen](https://github.com/matheeshapathirana/YouTube-Viewer-Bot/assets/140880739/f3954dd4-eca9-4f20-9b08-46f0801ca6d2)

**Comment by matheeshapathirana** [comment]
This repo is outdated and no longer working on this repo. Please use this repo maintained by MShawon: https://github.com/MShawon/YouTube-Viewer
